[workspace]

members = [
    "zokrates_core",
    "zokrates_cli",
    "zokrates_adsnark_cli",
    "zokrates_fs_resolver",
    "zokrates_github_resolver",
    "zokrates_stdlib",
    "zokrates_embed",
]
